# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tributary < Formula
  desc "Postgres subsetting & sync CLI"
  homepage "https://github.com/bhuneshvar-k/tributary"
  version "1.0.6"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/bhuneshvar-k/tributary/releases/download/v1.0.6/tributary_1.0.6_darwin_amd64.tar.gz"
      sha256 "86f3e1bb5dff9e2742eb39fbb5de6623f7620f055e91719482cd49b29ee92b75"

      define_method(:install) do
        bin.install "tributary"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/bhuneshvar-k/tributary/releases/download/v1.0.6/tributary_1.0.6_darwin_arm64.tar.gz"
      sha256 "c81a1ed81947808d19b1f70f5735979320c96317ba722a04a94e9ffcb9b697b3"

      define_method(:install) do
        bin.install "tributary"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/bhuneshvar-k/tributary/releases/download/v1.0.6/tributary_1.0.6_linux_amd64.tar.gz"
      sha256 "404007c1829cbf85ee890f2076d60f6b9c570faaaf10e1ecd9c6d425f329aa4b"
      define_method(:install) do
        bin.install "tributary"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/bhuneshvar-k/tributary/releases/download/v1.0.6/tributary_1.0.6_linux_arm64.tar.gz"
      sha256 "507d42f7dd918791160d35f1a776bdf6186e17ed473e8659c3bb6b7461282c4e"
      define_method(:install) do
        bin.install "tributary"
      end
    end
  end

  test do
    system "#{bin}/tributary", "--version"
  end
end
