# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tributary < Formula
  desc "Postgres subsetting & sync CLI"
  homepage "https://github.com/bhuneshvar-k/tributary"
  version "1.3.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/bhuneshvar-k/tributary/releases/download/v1.3.0/tributary_1.3.0_darwin_amd64.tar.gz"
      sha256 "4b0ba6d30b58d9eb531963daaae245c2921ea731096f4b928e37a8ea125a570c"

      define_method(:install) do
        bin.install "tributary"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/bhuneshvar-k/tributary/releases/download/v1.3.0/tributary_1.3.0_darwin_arm64.tar.gz"
      sha256 "034fea025228e0c64aff4fecb5c0e57d8721da68b3e781d309ee1e546817f894"

      define_method(:install) do
        bin.install "tributary"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/bhuneshvar-k/tributary/releases/download/v1.3.0/tributary_1.3.0_linux_amd64.tar.gz"
      sha256 "0b7e58bdc44121aae367a51d31411407f1453bc795d23a762b9e5bb6846d3cf2"
      define_method(:install) do
        bin.install "tributary"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/bhuneshvar-k/tributary/releases/download/v1.3.0/tributary_1.3.0_linux_arm64.tar.gz"
      sha256 "1cf341cda6b41a6b5b6a84f3d5159b27b2ef95169b01c69cbf0178c12b308af9"
      define_method(:install) do
        bin.install "tributary"
      end
    end
  end

  test do
    system "#{bin}/tributary", "--version"
  end
end
